server {
    listen 8099;
    root /var/www/html/trafficcontrol;
    index index.html index.php;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass unix:PHP_FPM_SOCK;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location ~ /\.tcsys {
        deny all;
    }

    location ~ /\.ht {
        deny all;
    }
}
